### PR TITLE
Added option for focus to follow the pointer

### PR DESCRIPTION
**Pull request by Techser**
As requested by #81

### CODE REVIEW

**Comment by Techser** [comment]
If this is change is alright and is accepted, I also think there should also be an option for the focus to follow the click. So clicking anywhere on an unfocused window focuses it.

**Comment by JLErvin** [comment]
> If this is change is alright and is accepted, I also think there should also be an option for the focus to follow the click. So clicking anywhere on an unfocused window focuses it.

This is already implemented, no? The user must have
```bash
~button1
    berryc pointer_focus
```
but this should focus windows by clicking anywhere within them. I believe other implementations would require grabbing buttons, which I would like to avoid if at all possible. My rationale here is that `berry` should "do one thing and do it well" - managing grabs should be deferred to something like `sxhkd` as much as possible. Although, I'm happy to discuss this from a practical perspective if you have other thoughts or ideas about alternative implementations.

**Comment by Techser** [comment]
That totally makes sense, I should have thought of that.

**Comment by JLErvin** [comment]
No worries. At a glance these changes look good - I'll give them a test after work today and merge them barring any issues. Thanks for contributing!

**Comment by Techser** [comment]
Awesome! I'm glad I could help.

**Comment by JLErvin** [comment]
Sorry, I've been bogged down with _life_. I have some additional changes I want to make, but I'll just add them in some future commits as I believe this is currently usable. Namely, I want to implement the following:
* Warp pointer functionality. I often use the cycle focus functionality of berry, which doesn't play nice with the enter notify since you'll likely have your pointer in the wrong window. I think that there should be an option to teleport the pointer to the active window.
* Focus following pointer should also work for decorations.
I'll implement these myself as I already have most of it working. Thanks again - cheers!

**Pull request merged**
